version: '3.1'

services:
  aws-user-service:
    container_name: "aws-user-container"
    image: "aws-user-image"
    build:
      context: .
      dockerfile: dockerfile_users
    ports:
      - "8081:8081"
    extra_hosts:
      - "DAYRHEPOSD001:10.7.35.67"
      - "DAYRHEPOSQ001:10.7.35.68"
    volumes:
      - scantt-volume:/scantt_shared_volume
    networks:
      - scantt-network
    entrypoint: ["java", "-Xms256m", "-Xmx512m", "-jar", "ttr-scantt-engine-instructions.jar", "--server.port=8081"]

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
